apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: REPLACEME_DOCKER_IMAGE_WITH_TAG
        ports:
        - name: nginx-port
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels: 
    app: nginx
  name: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
  type: NodePort
